# Generated by Django 4.2.13 on 2024-07-07 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Draft',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
